services:
  nassync:
    build: .
    container_name: nassync
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - nassync_data:/data
      - /path/to/nas/folder:/nas/folder:ro
      - /path/to/external/hdd:/hdd
    environment:
      - PORT=3000
      - TZ=Europe/London

volumes:
  nassync_data:
